const TIMEZONES: Array<string> = [
  "UTC-11 Niue Time (NUT)",
  "UTC-10 Samoa Standard Time (SST)",
  "UTC-9 Hawaii-Aleutian Standard Time (HAST)",
  "UTC-4 Eastern Standard Time (EST)",
  "UTC-7 Pacific Standard Time (PST)",
  "UTC-6 Mountain Standard Time (MST)",
  "UTC-5 Central Standard Time (CST)",
  "UTC-8 Alaska Standard Time (AKST)",
  "UTC-3 Atlantic Standard Time (AST)",
  "UTC-2 Brasília Time (BRT)",
  "UTC-1 Azores Standard Time (AZOT)",
  "GMT+0 Greenwich Mean Time (GMT)",
  "UTC+0 Coordinated Universal Time (UTC)",
  "UTC+1 Central European Time (CET)",
  "UTC+2 Eastern European Time (EET)",
  "UTC+3 Moscow Standard Time (MSK)",
  "UTC+4 Gulf Standard Time (GST)",
  "UTC+5 Pakistan Standard Time (PKT)",
  "UTC+6 Bangladesh Standard Time (BST)",
  "UTC+7 Indochina Time (ICT)",
  "UTC+8 China Standard Time (CST)",
  "UTC+9 Japan Standard Time (JST)",
  "UTC+10 Australian Eastern Standard Time (AEST)",
  "UTC+11 Solomon Islands Time (SBT)",
  "UTC+12 New Zealand Standard Time (NZST)",
];

export { TIMEZONES };
