const LANGUAGES: Array<string> = [
  "English",
  "Français (French)",
  "Español (Spanish)",
  "Hindi",
  "العربية (Arabic)",
  "Bengali",
  "Русский (Russian)",
  "Português (Portuguese)",
  "日本語 (Japanese)",
  "Deutsch (German)",
  "Pусский (Russian)",
  "中文 (Chinese)",
  "Italiano (Italian)",
  "हिन्दी (Hindi)",
  "한국어 (Korean)",
  "தமிழ (Tamil)",
  "ไทย (Thai)",
  "Nederlands (Dutch)",
  "čeština (Czech)",
  "Svenska (Swedish)",
  "Magyar (Hungarian)",
  "Polski (Polish)",
  "Ελληνικά (Greek)",
  "Türkçe (Turkish)",
  "ไทย (Thai)",
  "Filipino (Filipino)",
  "Indonesia (Indonesian)",
];

export { LANGUAGES };
